// Generated by https://quicktype.io
// ignore_for_file: depend_on_referenced_packages
import 'package:courseproject_ui_dd2022/domain/models/user.dart';
import 'package:json_annotation/json_annotation.dart';

part 'comment_model.g.dart';

@JsonSerializable()
class CommentModel {
  String id;
  String? postContent;
  User author;
  String creationDate;
  int reactionsCount;

  CommentModel({
    required this.id,
    this.postContent,
    required this.author,
    required this.creationDate,
    required this.reactionsCount,
  });

  factory CommentModel.fromJson(Map<String, dynamic> json) =>
      _$CommentModelFromJson(json);

  Map<String, dynamic> toJson() => _$CommentModelToJson(this);
}
