// Generated by https://quicktype.io
// ignore_for_file: depend_on_referenced_packages
import 'package:courseproject_ui_dd2022/domain/models/user.dart';
import 'package:json_annotation/json_annotation.dart';

part 'comment_model.g.dart';

@JsonSerializable()
class CommentModel {
  final String id;
  final String? postContent;
  final User author;
  final String creationDate;
  final int reactionsCount;
  final String? postId;

  CommentModel(
      {required this.id,
      this.postContent,
      required this.author,
      required this.creationDate,
      required this.reactionsCount,
      this.postId});

  factory CommentModel.fromJson(Map<String, dynamic> json) =>
      _$CommentModelFromJson(json);

  Map<String, dynamic> toJson() => _$CommentModelToJson(this);
}
