// Generated by https://quicktype.io
// ignore_for_file: depend_on_referenced_packages
import 'package:courseproject_ui_dd2022/domain/models/post_photo.dart';
import 'package:courseproject_ui_dd2022/domain/models/user.dart';
import 'package:json_annotation/json_annotation.dart';

part 'post_model.g.dart';

@JsonSerializable()
class PostModel {
  String id;
  String? postContent;
  List<PostPhoto> postAttachments;
  User author;
  String creationDate;
  int reactionsCount;
  int commentsCount;

  PostModel(
      {required this.id,
      this.postContent,
      required this.postAttachments,
      required this.author,
      required this.creationDate,
      required this.reactionsCount,
      required this.commentsCount});

  factory PostModel.fromJson(Map<String, dynamic> json) =>
      _$PostModelFromJson(json);

  Map<String, dynamic> toJson() => _$PostModelToJson(this);
}
